### ISSUE TITLE
the repo is broken

### ISSUE THREAD

**Issue by abma** [Balanced-Annihilation/Balanced-Annihilation#160]
$ git fetch
$ git reset --hard origin/master
```
error: unable to create symlink luarules/gadgets/AILoader.lua: File name too long
error: unable to create symlink luarules/gadgets/ai/BA/assistbehaviour.lua: File name too long
error: unable to create symlink luarules/gadgets/ai/BA/assisthandler.lua: File name too long
error: unable to create symlink luarules/gadgets/ai/BA/attackerbehaviour.lua: File name too long
error: unable to create symlink luarules/gadgets/ai/BA/attackhandler.lua: File name too long
error: unable to create symlink luarules/gadgets/ai/BA/bomberbehaviour.lua: File name too long
error: unable to create symlink luarules/gadgets/ai/BA/bomberhandler.lua: File name too long
error: unable to create symlink luarules/gadgets/ai/BA/bootbehaviour.lua: File name too long
error: unable to create symlink luarules/gadgets/ai/BA/buildsitehandler.lua: File name too long
error: unable to create symlink luarules/gadgets/ai/BA/cleanhandler.lua: File name too long
error: unable to create symlink luarules/gadgets/ai/BA/commonfunctions.lua: File name too long
error: unable to create symlink luarules/gadgets/ai/BA/countbehaviour.lua: File name too long
error: unable to create symlink luarules/gadgets/ai/BA/defendbehaviour.lua: File name too long
error: unable to create symlink luarules/gadgets/ai/BA/defendhandler.lua: File name too long
error: unable to create symlink luarules/gadgets/ai/BA/factoryregisterbehaviour.lua: File name too long
error: unable to create symlink luarules/gadgets/ai/BA/getunitfeaturetable.lua: File name too long
error: unable to create symlink luarules/gadgets/ai/BA/loshandler.lua: File name too long
error: unable to create symlink luarules/gadgets/ai/BA/maphandler.lua: File name too long
error: unable to create symlink luarules/gadgets/ai/BA/mexupgradebehaviour.lua: File name too long
error: unable to create symlink luarules/gadgets/ai/BA/raiderbehaviour.lua: File name too long
error: unable to create symlink luarules/gadgets/ai/BA/reclaimbehaviour.lua: File name too long
error: unable to create symlink luarules/gadgets/ai/BA/scouthandler.lua: File name too long
error: unable to create symlink luarules/gadgets/ai/BA/targethandler.lua: File name too long
error: unable to create symlink luarules/gadgets/ai/BA/taskAir.lua: File name too long
error: unable to create symlink luarules/gadgets/ai/BA/taskBot.lua: File name too long
error: unable to create symlink luarules/gadgets/ai/BA/taskBuild.lua: File name too long
error: unable to create symlink luarules/gadgets/ai/BA/taskEco.lua: File name too long
error: unable to create symlink luarules/gadgets/ai/BA/taskVeh.lua: File name too long
error: unable to create symlink luarules/gadgets/ai/BA/taskqueuebehaviour.lua: File name too long
error: unable to create symlink luarules/gadgets/ai/BA/taskqueues.lua: File name too long
error: unable to create symlink luarules/gadgets/ai/BA/turtlehandler.lua: File name too long
error: unable to create symlink luarules/gadgets/ai/BA/unitlists.lua: File name too long
error: unable to create symlink luarules/gadgets/ai/BA/wardbehaviour.lua: File name too long
error: unable to create symlink luarules/gadgets/ai/attackhandler.lua: File name too long
error: unable to create symlink luarules/gadgets/ai/preload/spring_lua/game.lua: File name too long
error: unable to create symlink luarules/gadgets/ai/preload/spring_lua/map.lua: File name too long
error: unable to create symlink luarules/gadgets/ai/preload/spring_lua/metal.lua: File name too long
error: unable to create symlink luarules/gadgets/ai/preload/spring_lua/unit.lua: File name too long
fatal: Could not reset index file to revision 'origin/master'.
```

please remove all symlinks! rapid isn't working any more.

**Comment by abma** [comment]
http://repos.springrts.com/ba/log.txt

**Comment by verybadsoldier** [comment]
fixed

**Comment by abma** [comment]
hu? nothing was changed?

it is not fixed!

i.e.
https://github.com/Balanced-Annihilation/Balanced-Annihilation

 LuaAI.lua still is a symlink

**Comment by abma** [comment]
the files have still an invalid mode!

**Comment by verybadsoldier** [comment]
> hu? nothing was changed?

Not true, fixed alot and clone works for me but you are right: there are still symlinks. Whoever managed to fill symlinks with file contents was a hellhound. 

Please try to be polite and stop ending every sentence with an exclamation mark. I will understand you either way. Thank you.

**Comment by abma** [comment]
> Please try to be polite and stop ending every sentence with an exclamation mark. I will understand you either way. Thank you.

i just responed politely to the "fixed" :-)

**Comment by abma** [comment]
see the pull request #161 

seems even github can't handle files with "symlink" mode probably :D

(the diff is invalid, only the mode was changed, not the file contents)

**Comment by abma** [comment]
> Not true, fixed alot and clone works for me but you are right: there are still symlinks. Whoever managed to fill symlinks with file contents was a hellhound.

true! since this issue was created nothing was changed...

**Comment by abma** [comment]
@verybadsoldier 

please don't force-push. this breaks a lot in a distributed version control system.

this breaks forks, pull requests and a lot more.

**Comment by verybadsoldier** [comment]
@abma 
Sorry for inconveniece of the force push but it was needed as a one-time action to rewrite a clean history and move BA10 out. It does not break anything but a manual interaction might be needed. If you have problems in that step than you can message me and I will help.

Also `master` branch is protected now so no further force pushes will occur.

**Comment by verybadsoldier** [comment]
> > Not true, fixed alot and clone works for me but you are right: there are still symlinks. Whoever managed to fill symlinks with file contents was a hellhound.
> 
> true! since this issue was created nothing was changed...

not!!1

Not really relevant anymore but if you look in that commit you see that e.g. `luarules/gadgets/AILoader.lua` is not a symlink anymore while it was when you created the PR as you can see in your original report.

look here:
https://github.com/Balanced-Annihilation/Balanced-Annihilation/tree/595f336f941f6813268b92af62d64a4b10234564/luarules/gadgets

**Comment by abma** [comment]
no clue, the force pushes makes it difficult / impossible to follow changes to the repo. :-/

thanks for merging + good that this is fixed! :)
