### ISSUE TITLE
unitsync error: [string "gamedata/featuredefs_post.lua"]:64: attempt to call field 'GetModOptions' (a nil value)

### ISSUE THREAD

**Issue by abma** [Balanced-Annihilation/Balanced-Annihilation#60]
Warning  /home/abma/dev/SpringLobby/src/log.cpp:195 Unitsync: Balanced Annihilation test-6614-f5397e4 ProcessUnits: luaParser.Execute() failed: [string "gamedata/defs.lua"]:38: [string "gamedata/defs.lua"]:26: error = 2, gamedata/featureDefs.lua, error = 2, gamedata/featuredefs_post.lua,

this error leads to https://springrts.com/phpbb/viewtopic.php?p=582140

reported a long time ago but ticket was ignored:

http://imolarpg.dyndns.org/trac/balatest/ticket/1136

**Comment by Ruwetuin** [comment]
fixed
(Spring.GetModOptions() function doesn' t exist when launched that way)

**Comment by Ruwetuin** [comment]
autohosting will now show up all units in unit restrictions tab, but after adding them as a restriction will not show them in the list with restrictions....

**Comment by abma** [comment]
i still get an error when the units are parsed:
Warning  /home/abma/dev/SpringLobby/src/log.cpp:195 Unitsync: Balanced Annihilation test-6745-6eedc82 ProcessUnits: luaParser.Execute() failed: [string "gamedata/defs.lua"]:38: [string "gamedata/defs.lua"]:26: error = 2, gamedata/unitDefs.lua, error = 2, gamedata/unitdefs_post.lua, [string "gamedata/alldefs_post.lua"]:75: attempt to call field 'GetModOptions' (a nil value)

**Comment by Ruwetuin** [comment]
fixed that.... but still not working... but... my springlobby.log seems to be not mentioning the stuff you have

**Comment by abma** [comment]
very likely a bug in springlobby:
https://github.com/springlobby/springlobby/issues/772

now at least the units show up again
